// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: current_task.sql

package repository

import (
	"context"
)

const getCurrentTask = `-- name: GetCurrentTask :one
SELECT id, current_task_id
FROM current_task
LIMIT 1
`

func (q *Queries) GetCurrentTask(ctx context.Context) (CurrentTask, error) {
	row := q.db.QueryRowContext(ctx, getCurrentTask)
	var i CurrentTask
	err := row.Scan(&i.ID, &i.CurrentTaskID)
	return i, err
}
