// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: current_task.sql

package repository

import (
	"context"
)

const switchCurrentTask = `-- name: SwitchCurrentTask :one
INSERT INTO current_task (
    task_id
) VALUES (
    (SELECT id FROM current_task LIMIT 1)
) returning id, current_entry_id
`

func (q *Queries) SwitchCurrentTask(ctx context.Context) (CurrentTask, error) {
	row := q.db.QueryRowContext(ctx, switchCurrentTask)
	var i CurrentTask
	err := row.Scan(&i.ID, &i.CurrentEntryID)
	return i, err
}
