// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: current_entry.sql

package repository

import (
	"context"
)

const getCurrentEntry = `-- name: GetCurrentEntry :one
SELECT id, current_entry_id
FROM current_entry
LIMIT 1
`

func (q *Queries) GetCurrentEntry(ctx context.Context) (CurrentEntry, error) {
	row := q.db.QueryRowContext(ctx, getCurrentEntry)
	var i CurrentEntry
	err := row.Scan(&i.ID, &i.CurrentEntryID)
	return i, err
}
