// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
)

type CurrentEntry struct {
	ID             int64
	CurrentEntryID sql.NullInt64
}

type CurrentTask struct {
	ID            int64
	CurrentTaskID sql.NullInt64
}

type Entry struct {
	ID             int64
	TaskID         int64
	StartTimestamp int64
	EndTimestamp   sql.NullInt64
	RecordedTime   sql.NullInt64
	Finished       int64
}

type Task struct {
	ID             int64
	Name           string
	StartTimestamp int64
	EndTimestamp   sql.NullInt64
	Finished       int64
	RecordedTime   sql.NullInt64
}
