// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entry.sql

package repository

import (
	"context"
)

const deleteEntry = `-- name: DeleteEntry :exec
DELETE FROM entry 
WHERE id = ?
`

func (q *Queries) DeleteEntry(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEntry, id)
	return err
}

const findAllEntries = `-- name: FindAllEntries :many
SELECT id, task_id, start_timestamp, end_timestamp, recorded_time, finished
FROM entry
`

func (q *Queries) FindAllEntries(ctx context.Context) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, findAllEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.StartTimestamp,
			&i.EndTimestamp,
			&i.RecordedTime,
			&i.Finished,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findEntryById = `-- name: FindEntryById :one
SELECT id, task_id, start_timestamp, end_timestamp, recorded_time, finished 
FROM entry 
WHERE id = ?
LIMIT 1
`

func (q *Queries) FindEntryById(ctx context.Context, id int64) (Entry, error) {
	row := q.db.QueryRowContext(ctx, findEntryById, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.StartTimestamp,
		&i.EndTimestamp,
		&i.RecordedTime,
		&i.Finished,
	)
	return i, err
}

const finishEntry = `-- name: FinishEntry :exec
UPDATE entry
SET finished=1
WHERE id = ?
`

func (q *Queries) FinishEntry(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, finishEntry, id)
	return err
}
